### ISSUE TITLE
Incremental load duplicate

### ISSUE THREAD

**Issue by tuanchris** [singer-io/tap-mysql#140]
Can anybody explain why the where statement is `>=` and not `>`? Implemented this way, shouldn't there be duplications of the watermarked records? 

https://github.com/singer-io/tap-mysql/blob/f6b0277a0020764b0834aa77651895a7cc550ad7/tap_mysql/sync_strategies/incremental.py#L64

**Comment by paultiplady** [comment]
Since I hit this elsewhere, I thought I'd leave some links to further discussion on this subject.

The Singer spec explicitly requires that taps should function this way, providing "at least once" semantics instead of "at most once semantics". This is to avoid missing data, since in theory if the replication key is a timestamp, you could have another entry added with the same timestamp after your job pulls from the DB (in case the write was in-flight when your job pulled from the table).

This means that the target must support de-duplication or Upsert to be able to use incremental updates.

More discussion in the Meltano repo: https://gitlab.com/meltano/meltano/-/issues/2504.

Singer issue discussing the issue: https://github.com/MeltanoLabs/Singer-Working-Group/issues/13
