### ISSUE TITLE
How to pull out data from multiple table join

### ISSUE THREAD

**Issue by carillpower** [singer-io/tap-mysql#77]
Hi,

I would like to check if the tap have possibility to pull out the data from multiple table join with several where clause ?

Could anyone share some tweak that I can make to make it possible ?

Thanks and appreciate for any advise

**Comment by dmosorast** [comment]
@carillpower Yes. The tap supports discovering and extracting records from views in the source MySQL Database. The [MySQL Documentation](https://dev.mysql.com/doc/refman/8.0/en/views.html) has in-depth information on the specifics of 
creating views, but, in general they are the results of a query that acts like a table.

So, in the context of the example database. A view showing just the bears from the animals table would look like this:

```
CREATE VIEW bears AS (
    SELECT * FROM animals WHERE name LIKE '%bear%';
)
```

And discovery mode should find two tables, `animals` and `bears`.

**Comment by carillpower** [comment]
Doing like this means we need to create the query massaging process outside of tap then tap will just extract out base on 1 views right.

Is it possible if inside the tap itself we code the create view script so that the where clause for the view creation we can input as dynamic value which taking from file like state.json ?

**Comment by dmosorast** [comment]
@carillpower That is correct, the tap is designed with an ELT mindset to discover all views and tables and provide sync strategies to consistently pull data from those tables and views.

To this end, it is written generically to provide as raw of data as possible, so that data modeling through joins and views can be done in the destination (redshift, postgres, snowflake, etc.). The idea here is that the shape of the data or needs of analysis could change over time, so this offers the most flexibility.

A side effect of having MySQL as the source, however, is that it gives all of the functionality to model the data *before* extraction by defining views, so that's another acceptable avenue.

However, if you want to dynamically adjust the query being used to select data for your specific use case, feel free to fork the repo and adjust the query building logic for your local extractions. You can find the code related to query building in [the common module](https://github.com/singer-io/tap-mysql/blob/master/tap_mysql/sync_strategies/common.py#L83-L94) and the module for the specific `sync_strategy` being used (for example, incremental sync mode [adds a `WHERE` clause](https://github.com/singer-io/tap-mysql/blob/master/tap_mysql/sync_strategies/incremental.py#L61) to the SQL generated by `common` for extracting based on a bookmark value in the state).

**Comment by carillpower** [comment]
@dmosorast  , thanks for ur output.. gonna hav a try on ur suggestion

**Comment by dmosorast** [comment]
No problem! Closing this for now.
